workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd example/ios
          pod install
          cd ../..
      - name: Check iOS project
        script: |
          ls -la example/ios/
          ls -la example/ios/Runner.xcodeproj/
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --export-options-plist=example/ios/ExportOptions.plist --verbose
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - taido.88241020248@st.ueh.edu.vn
        notify:
          success: true
          failure: true
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 