workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    working_directory: example
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad-hoc
        bundle_identifier: com.dohytai99.iosclone
    scripts:
      - name: Set up project
        script: |
          echo "Current working directory: $(pwd)"
          echo "List files in current directory:"
          ls -la
          echo "Setting up Flutter..."
          flutter doctor -v
      - name: Update bundle ID
        script: |
          cd ios
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.dohytai99.iosclone" Runner/Info.plist
          cd ..
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
    publishing:
      email:
        recipients:
          - taido.88241020248@st.ueh.edu.vn
        notify:
          success: true
          failure: true
        attachments:
          - build/ios/ipa/*.ipa
      scripts:
        - name: Save build info
          script: |
            echo "Build completed at $(date)"
            echo "IPA file location: build/ios/ipa/"
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 