workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd example
          flutter pub get
      - name: Install pods
        script: |
          cd example/ios
          pod install
          cd ../..
      - name: Flutter build ipa
        script: |
          cd example
          flutter build ipa --release
    artifacts:
      - example/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 