workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    working_directory: example
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up project
        script: |
          echo "Current working directory: $(pwd)"
          echo "List files in current directory:"
          ls -la
          echo "Setting up Flutter..."
          flutter doctor -v
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build ipa for TrollStore
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          cd ../../..
    artifacts:
      - build/ios/iphoneos/app.ipa
    publishing:
      email:
        recipients:
          - taido.88241020248@st.ueh.edu.vn
        notify:
          success: true
          failure: true
        attachments:
          - build/ios/iphoneos/app.ipa
      scripts:
        - name: Save build info
          script: |
            echo "Build completed at $(date)"
            echo "IPA file location: build/ios/iphoneos/app.ipa"
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 