workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    working_directory: example
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up project
        script: |
          echo "Current working directory: $(pwd)"
          echo "List files in current directory:"
          ls -la
          echo "Setting up Flutter..."
          flutter doctor -v
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build ipa for TrollStore
        script: |
          # Build iOS app
          flutter build ios --release --no-codesign
          
          # Debug: Check if build succeeded
          echo "Checking build directory..."
          ls -la build/ios/iphoneos/
          
          # Create Payload directory and IPA in multiple locations for safety
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          
          # Create IPA in build/ios/iphoneos
          cd build/ios/iphoneos
          zip -r app.ipa Payload
          cd ../../..
          
          # Also create IPA in build/outputs/ios
          mkdir -p build/outputs/ios
          cp build/ios/iphoneos/app.ipa build/outputs/ios/
          
          # Debug: List all locations
          echo "Contents of build/ios/iphoneos:"
          ls -la build/ios/iphoneos/
          echo "Contents of build/outputs/ios:"
          ls -la build/outputs/ios/
    artifacts:
      - build/**/outputs/**/*.ipa
      - build/ios/**/app.ipa
      - build/ios/iphoneos/app.ipa
    publishing:
      email:
        recipients:
          - taido.88241020248@st.ueh.edu.vn
        notify:
          success: true
          failure: true
      scripts:
        - name: Save build info
          script: |
            echo "Build completed at $(date)"
            echo "Current directory:"
            pwd
            echo "Contents of build directories:"
            ls -la build/ios/iphoneos/
            ls -la build/outputs/ios/
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 