workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    working_directory: example
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up project
        script: |
          flutter doctor -v
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build ipa for TrollStore
        script: |
          # Build iOS app
          flutter build ios --release --no-codesign
          
          # Create IPA
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          
          # Debug output
          echo "Current directory: $(pwd)"
          ls -la
    artifacts:
      - build/ios/iphoneos/app.ipa
    publishing:
      email:
        recipients:
          - taido.88241020248@st.ueh.edu.vn
        notify:
          success: true
          failure: true
      scripts:
        - name: Save build info
          script: |
            echo "Build completed at $(date)"
            echo "Current directory:"
            pwd
            echo "Contents of build directories:"
            ls -la build/ios/iphoneos/
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true 